name: Deploy Project

on:
  push:
     branches: [ "master" ]

jobs:
  deploy:
    runs-on:  ubuntu-latest
    environment: Production
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        
    - name: Publish project
      run: dotnet publish --configuration Release --output ./Publish TelegramGptBot/TelegramGptBot.csproj

      
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        port: ${{ secrets.EC2_PORT }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: ./Publish/
        target: ~/bot
    - name: Set Env variable
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
         export GPTApiToken=${{ secrets.GPTAPITOKEN }}
         export TelegramBotToken=${{ secrets.TELEGRAMBOTTOKEN }}
         export TelegramChatID=${{ secrets.TELEGRAMCHATID }}
    - name: Add EC2 SSH private key
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem
    - name: Run Bot
      run:   ssh -i "ec2_key.pem" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null  -f ec2-user@ec2-3-29-91-204.me-central-1.compute.amazonaws.com "nohup dotnet  ~/bot/Publish/TelegramGptBot.dll 2>&1 | logger -t GPTBot& || exit"
   
    - name: Cleanup private key
      run: rm -f ec2_key.pem




 
